# Generated by Django 5.2 on 2025-07-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_movimientoinventario"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="codigo",
            field=models.CharField(default="tmp", max_length=20, unique=True),
            preserve_default=False,
        ),
    ]