# Generated by Django 5.2.4 on 2025-07-05 22:43

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.apps import apps


def create_groups(apps, schema_editor):
    """Create default user groups with permissions."""
    admin_group, _ = Group.objects.get_or_create(name="admin")
    empleado_group, _ = Group.objects.get_or_create(name="empleado")

    core_models = [
        "Categoria",
        "Producto",
        "Proveedor",
        "Compra",
        "DetalleCompra",
        "Cliente",
        "Venta",
        "DetallesVenta",
        "Balance",
        "MovimientoInventario",
    ]

    permissions = Permission.objects.filter(content_type__app_label="core")
    admin_group.permissions.set(permissions)

    empleado_perms = permissions.filter(codename__startswith="view_") | permissions.filter(codename__startswith="add_venta") | permissions.filter(codename__startswith="add_detallesventa")
    empleado_group.permissions.set(empleado_perms)


def remove_groups(apps, schema_editor):
    Group.objects.filter(name__in=["admin", "empleado"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_venta_usuario"),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]