# Generated by Django 5.2.4 on 2025-07-09 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_movimientoinventario_producto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]