# Generated by Django 5.2.4 on 2025-07-11 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rename_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="es_ingrediente",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ComposicionProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_requerida",
                    models.FloatField(
                        help_text="Cantidad requerida del ingrediente (en gramos, litros, etc.)"
                    ),
                ),
                (
                    "ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.producto"
                    ),
                ),
                (
                    "producto_final",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredientes",
                        to="core.producto",
                    ),
                ),
            ],
        ),
    ]