# Generated by Django 5.2.4 on 2025-07-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_transaccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaccion",
            name="revisado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaccion",
            name="tipo_costo",
            field=models.CharField(
                blank=True,
                choices=[("fijo", "Fijo"), ("variable", "Variable")],
                max_length=10,
            ),
        ),
    ]