# Generated by Django 5.2.4 on 2025-07-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_add_tipo_costo"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaccion",
            name="actividad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("produccion", "Producción"),
                    ("distribucion", "Distribución"),
                    ("administracion", "Administración"),
                    ("otros", "Otros"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaccion",
            name="operativo",
            field=models.BooleanField(default=True),
        ),
    ]