# Generated by Django 5.2.4 on 2025-07-15 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_registroturno"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoteMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("fecha_recepcion", models.DateField()),
                (
                    "cantidad_inicial",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "cantidad_usada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fecha_agotado", models.DateField(blank=True, null=True)),
                (
                    "producto",
                    models.ForeignKey(
                        limit_choices_to={"es_ingrediente": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoteProductoFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("fecha_produccion", models.DateField()),
                (
                    "cantidad_producida",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "cantidad_vendida",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cantidad_devuelta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        limit_choices_to={"es_ingrediente": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.producto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="detallesventa",
            name="lote_final",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.loteproductofinal",
            ),
        ),
        migrations.CreateModel(
            name="UsoLoteMateriaPrima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "lote_materia_prima",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos",
                        to="core.lotemateriaprima",
                    ),
                ),
                (
                    "lote_producto_final",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos",
                        to="core.loteproductofinal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="loteproductofinal",
            name="ingredientes",
            field=models.ManyToManyField(
                related_name="lotes_finales",
                through="core.UsoLoteMateriaPrima",
                to="core.lotemateriaprima",
            ),
        ),
    ]