# Generated by Django 5.2.4 on 2025-07-15 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_lotemateriaprima_loteproductofinal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotemateriaprima",
            name="fecha_vencimiento",
            field=models.DateField(default=datetime.date.today),
        ),
    ]