# Generated by Django 5.2.4 on 2025-07-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_plan_produccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]