# Generated by Django 5.2.4 on 2025-07-19 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_rename_monthlyreport_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="es_ingrediente",
        ),
        migrations.AlterField(
            model_name="lotemateriaprima",
            name="producto",
            field=models.ForeignKey(
                limit_choices_to={"tipo__startswith": "ingred"},
                on_delete=django.db.models.deletion.CASCADE,
                to="core.producto",
            ),
        ),
        migrations.AlterField(
            model_name="loteproductofinal",
            name="producto",
            field=models.ForeignKey(
                limit_choices_to={"tipo__in": ["empanada", "producto_final", "bebida"]},
                on_delete=django.db.models.deletion.CASCADE,
                to="core.producto",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("empanada", "Empanada"),
                    ("ingredientes", "Ingredientes"),
                    ("producto_final", "Producto final"),
                    ("ingrediente", "Ingrediente"),
                    ("bebida", "Bebida"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: (
                apps.get_model("core", "Producto")
                .objects.filter(tipo="empanada")
                .update(tipo="producto_final")
            ),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: (
                apps.get_model("core", "Producto")
                .objects.filter(tipo="ingredientes")
                .update(tipo="ingrediente")
            ),
            reverse_code=migrations.RunPython.noop,
        ),
    ]