# Generated by Django 5.2.4 on 2025-07-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_replace_lote_with_fk"),
        ("core", "0029_unidad_medida"),
    ]

    operations = []