# Generated by Django 6.0 on 2025-12-17 23:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="almacen_origen",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="producto",
            name="codigo_barras",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="producto",
            name="control_por_lote",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="producto",
            name="control_por_serie",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="producto",
            name="costo_estandar",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="costo_promedio",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="descuento_base",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_alta",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_caducidad",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_costo",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="producto",
            name="impuesto",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="lead_time_dias",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producto",
            name="merma_porcentaje",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="nivel_reorden",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="rendimiento_receta",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="stock_seguridad",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="unidad_empaque",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="vida_util_dias",
            field=models.PositiveIntegerField(default=0),
        ),
    ]