# Generated by Django 6.0 on 2025-12-17 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_producto_activo_producto_almacen_origen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loteproductofinal",
            name="costo_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]