# Generated by Django 6.0 on 2025-12-18 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_loteproductofinal_costo_unitario"),
    ]

    operations = [
        migrations.AddField(
            model_name="devolucionproducto",
            name="clasificacion",
            field=models.CharField(
                choices=[("reintegro", "Reintegro"), ("merma", "Merma")],
                default="merma",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="loteproductofinal",
            name="cantidad_descartada",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]