# Generated by Django 5.2.4 on 2025-07-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_devolucionproducto"),
    ]

    operations = [
        migrations.AddField(
            model_name="composicionproducto",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="composicionproducto",
            name="lote",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="detallesventa",
            name="lote",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]