# Generated by Django 5.2.4 on 2025-07-15 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_composicionproducto_activo_composicionproducto_lote_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialPrecio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("costo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="core.producto",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]