# Generated by Django 5.2.4 on 2025-07-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_historialprecio"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("month", "year")},
            },
        ),
    ]