# Generated by Django 5.2.4 on 2025-07-15 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_production_planning"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroTurno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("manana", "Mañana"),
                            ("tarde", "Tarde"),
                            ("noche", "Noche"),
                        ],
                        max_length=10,
                    ),
                ),
                ("produccion", models.PositiveIntegerField(default=0)),
                (
                    "ventas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "horas_trabajadas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("productos_defectuosos", models.PositiveIntegerField(default=0)),
                ("devoluciones", models.PositiveIntegerField(default=0)),
                ("observaciones", models.TextField(blank=True)),
                ("empleados", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-fecha", "turno"],
            },
        ),
    ]