# Generated by Django 5.2.4 on 2025-07-19 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_es_ingrediente"),
    ]

    def create_units(apps, schema_editor):
        UnidadMedida = apps.get_model("core", "UnidadMedida")
        units = [
            ("Unidad", "u"),
            ("Kilogramo", "kg"),
            ("Gramo", "g"),
            ("Libra", "lb"),
            ("Botella", "botella"),
        ]
        for nombre, ab in units:
            UnidadMedida.objects.get_or_create(abreviatura=ab, defaults={"nombre": nombre})

    def migrate_products(apps, schema_editor):
        UnidadMedida = apps.get_model("core", "UnidadMedida")
        Producto = apps.get_model("core", "Producto")
        mapping = {
            "u": "u",
            "unidad": "u",
            "unidades": "u",
            "kg": "kg",
            "g": "g",
            "lb": "lb",
            "botella": "botella",
        }
        for prod in Producto.objects.all():
            ab = mapping.get(prod.unidad_media, "u") if isinstance(prod.unidad_media, str) else "u"
            unidad = UnidadMedida.objects.filter(abreviatura=ab).first()
            prod.unidad_media = unidad
            prod.save(update_fields=["unidad_media"])

    operations = [
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("abreviatura", models.CharField(max_length=10)),
            ],
            options={"verbose_name_plural": "Unidades de medida"},
        ),
        migrations.AlterField(
            model_name="producto",
            name="unidad_media",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.unidadmedida"
            ),
        ),
        migrations.RunPython(create_units, migrations.RunPython.noop),
        migrations.RunPython(migrate_products, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="producto",
            name="unidad_media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.unidadmedida"
            ),
        ),
    ]