# Generated by Django 5.2.4 on 2025-07-19 04:45

import django.db.models.deletion
from django.db import migrations, models


def migrate_lote_to_fk(apps, schema_editor):
    DevolucionProducto = apps.get_model("core", "DevolucionProducto")
    LoteProductoFinal = apps.get_model("core", "LoteProductoFinal")
    for devolucion in DevolucionProducto.objects.all():
        codigo = getattr(devolucion, "lote", None)
        if not codigo:
            continue
        try:
            lote_final = LoteProductoFinal.objects.get(codigo=codigo)
        except LoteProductoFinal.DoesNotExist:
            continue
        devolucion.lote_final = lote_final
        devolucion.save(update_fields=["lote_final"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_es_ingrediente"),
    ]

    operations = [
        migrations.AddField(
            model_name="devolucionproducto",
            name="lote_final",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.loteproductofinal",
            ),
        ),
        migrations.RunPython(
            migrate_lote_to_fk, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="devolucionproducto",
            name="lote",
        ),
    ]