# Generated by Django 6.0 on 2025-12-18 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_familia_producto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="compra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos",
                to="core.compra",
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="devolucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos",
                to="core.devolucionproducto",
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="operacion_tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("venta", "Venta"),
                    ("compra", "Compra"),
                    ("devolucion", "Devolución"),
                    ("ajuste", "Ajuste manual"),
                    ("reorden", "Reorden automático"),
                    ("eliminacion", "Eliminación de producto"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos",
                to="core.venta",
            ),
        ),
    ]