# Generated by Django 5.2.9 on 2025-12-20 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_gasto_recurrente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidadmedida'),
        ),
    ]
