# Generated by Django 6.0 on 2025-12-24 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_devolucionproducto_venta_ajusteinventario_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacturaVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=30, unique=True)),
                ("pdf", models.FileField(upload_to="facturas/")),
                ("enviado", models.BooleanField(default=False)),
                ("enviado_a", models.EmailField(blank=True, max_length=254, null=True)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factura",
                        to="core.venta",
                    ),
                ),
            ],
        ),
    ]